#pragma once

#include "ast_leaf.h"

namespace jhin
{
namespace ast
{

#define AST_NON_LEAF_START  1024

enum EASTNonLeaf
{
    AST_NON_LEAF_ASSIGN = AST_NON_LEAF_START,
    AST_NON_LEAF_WHILE,
    AST_NON_LEAF_IF,
    AST_NON_LEAF_IF_ELSE,
    AST_NON_LEAF_CLASS,
    AST_NON_LEAF_CLASS_INHERITS,
    AST_NON_LEAF_FUNCTION,
    AST_NON_LEAF_IS_VOID,
    AST_NON_LEAF_NOT,
    AST_NON_LEAF_NEW,

    AST_NON_LEAF_PLUS,
    AST_NON_LEAF_MINUS,
    AST_NON_LEAF_STAR,
    AST_NON_LEAF_SLASH,

    AST_NON_LEAF_EQ,
    AST_NON_LEAF_LT,
    AST_NON_LEAF_LE,
    AST_NON_LEAF_GT,
    AST_NON_LEAF_GE,

    AST_NON_LEAF_LAMBDA,
    AST_NON_LEAF_FN_CALL,
    AST_NON_LEAF_OBJECT_FN_CALL,
    AST_NON_LEAF_OBJECT_FN_CALL_DISPATCH,
    AST_NON_LEAF_EXP_OBJECT_FN_CALL,
    AST_NON_LEAF_EXP_OBJECT_FN_CALL_DISPATCH,

    AST_NON_LEAF_LET_IN,
    AST_NON_LEAF_RETURN,
    AST_NON_LEAF_CASE_OF_OTHERWISE,

    AST_NON_LEAF_DCL,
};


};  /* namsspace ast */
};  /* namespace jhin */

